"use client"

// import { Metadata } from 'next'
import './globals.css'
import { Provider } from 'react-redux'
import store from '@/lib/store'
import HomeLayout from './homeLayout'
import Notification from "./components/notifications/notify"




// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, }: { children: React.ReactNode }) {

    return (
        <html lang="en">
            <Provider store={store}>
                <body className='' >
                    <Notification />
                    <HomeLayout />
                    {children}
                </body>
            </Provider>
        </html>
    )
}


