import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import CartIcon from './_components/svg/svg/cart'
import SearchIcon from './_components/svg/svg/search'
import Button from './_components/button'
import MenuIcon from './_components/svg/svg/menu'
import { Badge } from 'antd'
// import { inter, roboto } from './font'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">

      <body className='' >
        <Header />
        {children}
      </body>
    </html>
  )
}

const Header = () => {
  return (
    <div className=" py-2 bg-primaryBackgroundColor shadow-lg shadow-slate-100 ">
      <div className='flex justify-between items-center w-[90%] mx-auto'>

        <div className="flex gap-4 items-center ">
          <div className='flex-content'>
            <div className="flex sm:flex md:hidden lg:hidden xl:hidden">
              <MenuIcon color="green" stroke='green' />
            </div>
            <h1 className="font-bold text-[1.3rem]">Foodie</h1>


          </div>
          <nav className="hidden sm:hidden md:flex md:gap-4 lg:flex lg:gap-4">
            <Link href="/"> <h3 className='link-style'>Home</h3></Link>
            <Link href="/"> <h3 className='link-style'>Recommendation</h3></Link>
          </nav>
        </div>

        <div className='flex-content'>

          <div className='bg-green-100 p-2 rounded-full'>
            <SearchIcon color="none" stroke='green' />

          </div>

          <Button className='hidden sm:hidden md:flex lg:flex'>
            <h4>
              Login/Sign Up
            </h4>
          </Button>
          <Badge count={3}>
            <CartIcon color="green" />

          </Badge>

        </div>
      </div>

    </div>
  )
}
